---
# tasks file for docker-trust
- name: Upload privkey
  copy:
    src: sigkeypriv.pem
    dest: /home/agentuser/sigkeypriv.pem
    owner: agentuser
    group: agentuser
    mode: '0600' 

- name: Docker Trust Key load
  become: yes
  become_user: agentuser
  command: docker trust key load /home/agentuser/sigkeypriv.pem --name sigkeypriv
  environment:
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: "12345678" 
  register: cmd_out

- debug:
    msg: "{{ cmd_out.stdout }}"

- name: Remove sigkeypriv file
  file:
    path: /home/agentuser/sigkeypriv.pem
    state: absent
...
