---
# tasks file for deploy-imagescan
# https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
- name: Download Trivy
  get_url:
    url: "https://github.com/aquasecurity/trivy/releases/download/v{{ trivyVersion }}/trivy_{{ trivyVersion }}_Linux-64bit.deb"
    dest: "/home/management/trivy.dep"

- name: Install Trivy
  become: yes
  command: dpkg -i /home/management/trivy.dep
  register: dpkg_out

- debug:
    msg: "{{ dpkg_out.stdout }}"

- name: Remove Download
  file:
    path: "/home/management/trivy.dep"
    state: absent

- name: Check version
  command: trivy -v
  register: version_out

- debug:
    msg: "{{ version_out.stdout }}"
...

