name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_HOST: 'unix:///run/user/1001/docker.sock'
  DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.TRUSTREPOPWD }}
  DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: ${{ secrets.TRUSTROOTPWD }}
  DOCKER_CONTENT_TRUST: '1'

jobs:

  build:

    runs-on: self-hosted 

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Docker version
        run: docker version

      - uses: docker/login-action@v3
        name: Dockerhub login
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Load joroprivkey 
        run: docker trust key load --name joroprivkey ~/.docker/trust/private/7608e6e556b0d54092ef541f6613ea894f0602a3b684bcc424997dda32fb7cbb.key

      - name: Add delegation Pub key to a spesific image repository with Global Unique name (GUN) in Notary server
        run: docker trust signer add --key /home/agentuser/Content_trust/jorokey.pub joro jrcjoro1/mypythonapp 

      - name: Build the Docker image
        run: docker build -t jrcjoro1/mypythonapp:$GITHUB_SHA .

      - name: Trivy
        run: trivy image --severity HIGH,CRITICAL --format table --exit-code 0 --ignore-unfixed --vuln-type os,library jrcjoro1/mypythonapp:$GITHUB_SHA

      - name: Push Docker image to Dockerhub
        run: docker push jrcjoro1/mypythonapp:$GITHUB_SHA

      - name: Inspect
        run: docker trust inspect --pretty jrcjoro1/mypythonapp:$GITHUB_SHA

      - name: Vars
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_WORKFLOW_SHA: $GITHUB_WORKFLOW_SHA"
          echo "RUNNER_NAME: $RUNNER_NAME"
          echo "RUNNER_DEBUG: $RUNNER_DEBUG"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
