name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_HOST: 'unix:///run/user/1001/docker.sock'
  DOCKER_CONTENT_TRUST: '1'
  DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.TRUSTREPOPWD }}
#  DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: ${{ secrets.TRUSTROOTPWD }}
  APP: 'mypythonapp1'
  DOCKERHUB: 'jrcjoro1'

jobs:

  build:

    runs-on: self-hosted 

    steps:
      - name: Check if DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE is set
        if: ${{ env.DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE == '' }}
        run: echo "Secret DCT REPO is not set"

#      - name: Check if DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE is set
#        if: ${{ env.DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE == '' }}
#        run: echo "Secret DCT ROOT is not set"

      - uses: actions/checkout@v4
        name: Checkout

      - name: Docker version
        run: docker version

      - uses: docker/login-action@v3
        name: Dockerhub login
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Load newsigner with DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE set to NEWSIGNER pwd
        run: docker trust key load --name newsigner ~/.docker/trust/private/8eb496d6539a0371e2c817b6f3ace87e21b5df946cad465fe6cc2eefcf9f850c.key
        env:
          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.TRUSTNEWSIGNER }}

#      - name:  Add newsigner pub key with DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE set to what
#        run:  docker trust signer add --key ~/Content_trust/delegation.crt newsigner ${{ secrets.DOCKERHUB_USERNAME }}/$APP 
#        env:
#          DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: ${{ secrets.TRUSTROOTPWD }}  

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$APP:$GITHUB_SHA .

      - name: Trivy
        run: trivy image --severity HIGH,CRITICAL --format table --exit-code 0 --ignore-unfixed --vuln-type os,library ${{ secrets.DOCKERHUB_USERNAME }}/$APP:$GITHUB_SHA

      - name: Push Docker image to Dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$APP:$GITHUB_SHA

      - name: Inspect
        run: docker trust inspect --pretty ${{ secrets.DOCKERHUB_USERNAME }}/$APP

      - name: Vars
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_WORKFLOW_SHA: $GITHUB_WORKFLOW_SHA"
          echo "RUNNER_NAME: $RUNNER_NAME"
          echo "RUNNER_DEBUG: $RUNNER_DEBUG"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
