name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PR_NUM: ${{ github.event.number }}
  BR_NAME: ${{ github.event.pull_request.head.ref }}
  UPDATED_AT: ${{ github.event.pull_request.updated_at }}

jobs:

  build:

    runs-on: self-hosted 

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mypythonapp:$(date +%s)

    - name: "Vars"
      run: |
        echo "F: $PR_NUM"
        echo "S: $BR_NAME"
        echo "T: $UPDATED_AT"
