name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_HOST: 'unix:///run/user/1001/docker.sock'
  DOCKER_CONTENT_TRUST: '1'
  DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.TRUSTREPOPWD }}
#  DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: ${{ secrets.TRUSTROOTPWD }} not needed beacuse repo is already manually initialized
  APP: 'mypythonapp1'
  DOCKERHUB: 'jrcjoro1'
  CHART_VER: '0.0.2'
  REGISTRY: 'docker.io'

jobs:

  build:

    runs-on: self-hosted 

    steps:
      - name: Check if DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE is set
        if: ${{ env.DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE == '' }}
        run: echo "Secret DCT REPO is not set"

#      - name: Check if DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE is set
#        if: ${{ env.DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE == '' }}
#        run: echo "Secret DCT ROOT is not set"

      - uses: actions/checkout@v4
        name: Checkout

      - name: Docker version
        run: docker version

      - uses: docker/login-action@v3
        name: Dockerhub login
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Inspect
        run: docker trust inspect --pretty ${{ secrets.DOCKERHUB_USERNAME }}/$APP

      - name: Load newsigner2 with DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE set to NEWSIGNER2 
        run: docker trust key load --name newsigner2 ~/.docker/trust/private/950ec70deaca8bc2f0590fc19f88626fec7e0bfd77be63f3b2764b43f249fa94.key
        env:
          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.TRUSTNEWSIGNER2 }}

      - name: Signer add with TRUSTREPOPWD 
        run:  docker trust signer add --key ~/Content_trust/newsigner2.pub newsigner2 docker.io/${{ secrets.DOCKERHUB_USERNAME }}/$APP 
        env:
          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.TRUSTREPOPWD }}

      - name: Check if newsigner2 is added
        run: docker trust inspect --pretty ${{ secrets.DOCKERHUB_USERNAME }}/$APP
      
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$APP:$GITHUB_SHA .

      - name: Trivy
        run: trivy image --severity HIGH,CRITICAL --format table --exit-code 0 --ignore-unfixed --vuln-type os,library ${{ secrets.DOCKERHUB_USERNAME }}/$APP:$GITHUB_SHA

      - name: Sign and push Docker image to Dockerhub
        run: docker trust sign docker.io/${{ secrets.DOCKERHUB_USERNAME }}/$APP:$GITHUB_SHA
        env:
          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.TRUSTNEWSIGNER2 }}

      - name: Inspect
        run: docker trust inspect --pretty ${{ secrets.DOCKERHUB_USERNAME }}/$APP

      - name: Run edit_chart script in Runner
        run: ~/bin/edit_chart.sh $CHART_VER $GITHIB_SHA $APP $REGISTRY $GITHUB_SHA
        shell: bash

      - name: Vars
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_WORKFLOW_SHA: $GITHUB_WORKFLOW_SHA"
          echo "RUNNER_NAME: $RUNNER_NAME"
          echo "RUNNER_DEBUG: $RUNNER_DEBUG"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
